case(270) 
!SRF = tigr_tpw_trans_ch1_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  3.6998e-06,  5.0675e-05, -3.3499e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0100e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  6.2750e-05,  3.0561e-03, -8.3073e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8569e-02
Solar_Rtm%Tau_O3( 1) =  4.7051e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch3_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/ -4.1299e-05,  1.5030e-03, -2.9715e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.7029e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_ch4_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2738e+00,  1.8398e+00, -1.0312e-01/)
Solar_Rtm%Tau_Ray(26) =  2.5810e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  2.6543e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00

!SRF = tigr_tpw_trans_ch5_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -1.7666e-05,  1.0591e-03, -9.8830e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.4007e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.3108e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00

!SRF = tigr_tpw_trans_ch6_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.9361e-04,  3.0409e-03, -1.1826e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6633e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  2.9395e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_ch7_resp_g16.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  3.9973e-04,  2.0678e-02, -9.5447e-04/)
Solar_Rtm%Tau_Ray(20) =  2.1935e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  3.3747e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(271) 
!SRF = tigr_tpw_trans_ch1_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  3.8492e-06,  5.1239e-05, -3.9976e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0021e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  7.8288e-05,  3.0282e-03, -7.4102e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8814e-02
Solar_Rtm%Tau_O3( 1) =  4.7445e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch3_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/ -1.3455e-05,  1.4371e-03, -2.3229e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.6993e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_ch4_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.3328e+00,  1.8217e+00, -1.0038e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6204e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.7726e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00

!SRF = tigr_tpw_trans_ch5_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.8946e-05,  1.0648e-03, -1.1633e-05/)
Solar_Rtm%Tau_Ray( 6) =  1.4002e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.2943e-02

!SRF = tigr_tpw_trans_ch6_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.6756e-04,  3.1410e-03, -1.2049e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6915e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.2330e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_ch7_resp_g17.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  8.3411e-04,  2.5816e-02, -1.2675e-03/)
Solar_Rtm%Tau_Ray(20) =  2.3326e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  2.9383e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
