case(270) 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.0976e-06,  5.1192e-05, -4.5276e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0117e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.0781e-04,  3.0131e-03, -7.5446e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8779e-02
Solar_Rtm%Tau_O3( 1) =  4.5443e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  4.5128e-06,  1.5223e-03, -3.2667e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.6950e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2994e+00,  1.8412e+00, -1.0906e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6229e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.7467e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/  2.8819e-05,  9.5829e-04,  6.5462e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.3928e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.2580e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.8007e-04,  2.9631e-03, -1.1315e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6684e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.1249e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_16_abi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  4.4318e-04,  2.3993e-02, -1.1494e-03/)
Solar_Rtm%Tau_Ray(20) =  2.2932e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  3.0228e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(271) 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.9039e-06,  4.9691e-05,  5.8542e-08/)
Solar_Rtm%Tau_Ray( 3) =  2.0122e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  4.4817e-05,  3.1352e-03, -9.5973e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.9081e-02
Solar_Rtm%Tau_O3( 1) =  4.7786e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  1.1352e-05,  1.5409e-03, -3.1745e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.6952e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.3288e+00,  1.8344e+00, -1.0356e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6365e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.7890e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.1605e-05,  1.0483e-03, -1.0218e-05/)
Solar_Rtm%Tau_Ray( 6) =  1.3874e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.2793e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -2.0707e-04,  3.2254e-03, -1.3040e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6919e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.1235e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_17_abi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.4725e-04,  2.6163e-02, -1.3225e-03/)
Solar_Rtm%Tau_Ray(20) =  2.7009e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  2.9669e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(272) 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.2635e-06,  5.0733e-05, -1.3529e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0120e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  6.6423e-05,  3.0724e-03, -8.2564e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8652e-02
Solar_Rtm%Tau_O3( 1) =  4.6303e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  3.0346e-06,  1.5707e-03, -3.0033e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.7086e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2826e+00,  1.8800e+00, -1.1201e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6293e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.7638e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.1946e-05,  1.0642e-03, -7.0704e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.4094e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.3207e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -2.0529e-04,  3.3254e-03, -1.3542e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6788e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.0239e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_18_abi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  2.5196e-04,  2.0707e-02, -9.7187e-04/)
Solar_Rtm%Tau_Ray(20) =  2.4081e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  3.2571e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(273) 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.8546e-06,  4.8301e-05,  1.5331e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0059e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  5.2577e-05,  3.0791e-03, -8.8140e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8537e-02
Solar_Rtm%Tau_O3( 1) =  4.6463e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  1.8070e-05,  1.6085e-03, -3.8330e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.7001e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2263e+00,  1.8795e+00, -1.1002e-01/)
Solar_Rtm%Tau_Ray(26) =  2.5880e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  2.6536e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -6.5102e-07,  1.0285e-03, -4.0765e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.3983e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.3048e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.5833e-04,  3.0262e-03, -1.1109e-04/)
Solar_Rtm%Tau_Ray( 7) =  3.6557e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  2.9704e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_goes_19_abi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  1.6102e-04,  2.1149e-02, -1.0334e-03/)
Solar_Rtm%Tau_Ray(20) =  2.2799e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  3.3852e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
