case(173) 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  3.9164e-06,  5.2060e-05, -2.9382e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0096e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  2.5954e-05,  7.0107e-04, -8.5257e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.4516e-01
Solar_Rtm%Tau_O3( 4) =  4.8710e-06
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  8.8065e-05,  2.9251e-03, -6.6689e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.9083e-02
Solar_Rtm%Tau_O3( 1) =  4.7543e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  7.1923e-05,  3.6581e-03, -1.1450e-04/)
Solar_Rtm%Tau_Ray( 2) =  1.7664e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.5383e-06,  1.0109e-03, -3.1218e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.3871e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.2322e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.3023e-04,  1.4114e-03, -4.5980e-05/)
Solar_Rtm%Tau_Ray( 7) =  3.5438e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.3471e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_8_ahi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  1.2857e-03,  2.6675e-02, -1.2884e-03/)
Solar_Rtm%Tau_Ray(20) =  2.4455e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  2.9857e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
case(174) 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  5.7958e-06,  4.9444e-05,  1.8629e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0186e-01
Solar_Rtm%Tau_O3( 3) =  1.3824e-10
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  1.6854e-05,  7.1086e-04, -8.9678e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.4473e-01
Solar_Rtm%Tau_O3( 4) =  4.4056e-06
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  7.3591e-05,  2.9281e-03, -8.3073e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8449e-02
Solar_Rtm%Tau_O3( 1) =  4.6652e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  8.0813e-05,  3.6850e-03, -1.2360e-04/)
Solar_Rtm%Tau_Ray( 2) =  1.7617e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch05.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -4.6404e-05,  1.1087e-03, -1.4572e-05/)
Solar_Rtm%Tau_Ray( 6) =  1.4081e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.3149e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch06.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.3080e-04,  1.3853e-03, -4.3671e-05/)
Solar_Rtm%Tau_Ray( 7) =  3.5310e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.1960e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
 
!SRF = tigr_tpw_trans_rtcoef_himawari_9_ahi_srf_ch07.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  4.0006e-03,  4.4322e-02, -2.4431e-03/)
Solar_Rtm%Tau_Ray(20) =  2.8213e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  2.1382e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
