case(173) 
!SRF = tigr_tpw_trans_ch1_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.5112e-06,  5.1395e-05, -1.9105e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0146e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  3.5560e-05,  6.7475e-04, -2.1035e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.4393e-01
Solar_Rtm%Tau_O3( 4) =  3.8917e-06
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00

!SRF = tigr_tpw_trans_ch3_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  8.7089e-05,  2.9454e-03, -7.7288e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.8655e-02
Solar_Rtm%Tau_O3( 1) =  4.6808e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch4_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  1.0741e-04,  3.6017e-03, -1.0748e-04/)
Solar_Rtm%Tau_Ray( 2) =  1.7662e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_ch5_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/  4.5871e-06,  1.0012e-03,  3.0030e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.4074e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.2504e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00

!SRF = tigr_tpw_trans_ch6_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.3006e-04,  1.3990e-03, -4.6335e-05/)
Solar_Rtm%Tau_Ray( 7) =  3.5377e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  3.3139e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_ch7_resp_ahi.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  1.2103e-03,  2.6850e-02, -1.3311e-03/)
Solar_Rtm%Tau_Ray(20) =  2.5785e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  2.9989e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
