!SRF = tigr_tpw_trans_ch1_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.2798e-04,  3.9665e-03, -9.4883e-05/)
Solar_Rtm%Tau_Ray( 1) =  5.5592e-02
Solar_Rtm%Tau_O3( 1) =  3.5224e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00
!SRF = tigr_tpw_trans_ch2_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  5.2841e-04,  5.0938e-03, -2.2222e-04/)
Solar_Rtm%Tau_Ray( 2) =  1.7571e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
!SRF = tigr_tpw_trans_ch3_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  4.0729e-06,  5.9610e-05, -6.1466e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0820e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00
!SRF = tigr_tpw_trans_ch4_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  2.0643e-05,  3.4106e-04, -4.6013e-07/)
Solar_Rtm%Tau_Ray( 4) =  1.0242e-01
Solar_Rtm%Tau_O3( 4) =  6.2138e-05
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00
!SRF = tigr_tpw_trans_ch5_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 5,:) = (/ -1.2070e-04,  4.4479e-03, -1.6284e-04/)
Solar_Rtm%Tau_Ray( 5) =  3.9553e-03
Solar_Rtm%Tau_O3( 5) =  0.0000e+00
Solar_Rtm%Tau_CO2( 5) =  3.1439e-04
Solar_Rtm%Tau_CH4( 5) =  0.0000e+00
!SRF = tigr_tpw_trans_ch6_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -3.1191e-05,  9.1425e-04, -8.7464e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.3261e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  7.4501e-03
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00
!SRF = tigr_tpw_trans_ch7_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/  1.4032e-03,  1.5792e-02, -7.4784e-04/)
Solar_Rtm%Tau_Ray( 7) =  4.6378e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  1.9085e-02
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00
!SRF = tigr_tpw_trans_ch8_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 8,:) = (/  0.0000e+00,  0.0000e+00,  0.0000e+00/)
Solar_Rtm%Tau_Ray( 8) =  3.4396e-01
Solar_Rtm%Tau_O3( 8) =  0.0000e+00
Solar_Rtm%Tau_CO2( 8) =  0.0000e+00
Solar_Rtm%Tau_CH4( 8) =  0.0000e+00
!SRF = tigr_tpw_trans_ch9_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef( 9,:) = (/  1.6193e-05,  2.4601e-04, -5.4344e-07/)
Solar_Rtm%Tau_Ray( 9) =  2.5833e-01
Solar_Rtm%Tau_O3( 9) =  0.0000e+00
Solar_Rtm%Tau_CO2( 9) =  0.0000e+00
Solar_Rtm%Tau_CH4( 9) =  0.0000e+00
!SRF = tigr_tpw_trans_ch20_resp_myd.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  6.2229e-03,  5.3742e-02, -2.9021e-03/)
Solar_Rtm%Tau_Ray(20) =  3.7245e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.8466e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
!SRF = tigr_tpw_trans_ch1_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  5.8407e-05,  4.0782e-03, -1.2187e-04/)
Solar_Rtm%Tau_Ray( 1) =  5.5456e-02
Solar_Rtm%Tau_O3( 1) =  3.5057e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  5.0446e-04,  5.3623e-03, -2.4300e-04/)
Solar_Rtm%Tau_Ray( 2) =  1.7538e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_ch3_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  5.3701e-06,  5.7457e-05, -1.4299e-07/)
Solar_Rtm%Tau_Ray( 3) =  2.0929e-01
Solar_Rtm%Tau_O3( 3) =  0.0000e+00
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_ch4_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  1.2671e-05,  3.8263e-04, -1.4133e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.0191e-01
Solar_Rtm%Tau_O3( 4) =  6.4149e-05
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00

!SRF = tigr_tpw_trans_ch5_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 5,:) = (/ -1.1234e-04,  4.1652e-03, -1.4420e-04/)
Solar_Rtm%Tau_Ray( 5) =  3.9409e-03
Solar_Rtm%Tau_O3( 5) =  0.0000e+00
Solar_Rtm%Tau_CO2( 5) =  2.8529e-04
Solar_Rtm%Tau_CH4( 5) =  0.0000e+00

!SRF = tigr_tpw_trans_ch6_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -3.2843e-05,  9.5992e-04, -6.3558e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.3212e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  6.2353e-03
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00

!SRF = tigr_tpw_trans_ch7_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/  1.4325e-03,  1.5859e-02, -7.7206e-04/)
Solar_Rtm%Tau_Ray( 7) =  4.6692e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  1.7954e-02
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_ch8_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 8,:) = (/  0.0000e+00,  0.0000e+00,  0.0000e+00/)
Solar_Rtm%Tau_Ray( 8) =  3.4923e-01
Solar_Rtm%Tau_O3( 8) =  0.0000e+00
Solar_Rtm%Tau_CO2( 8) =  0.0000e+00
Solar_Rtm%Tau_CH4( 8) =  0.0000e+00

!SRF = tigr_tpw_trans_ch9_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef( 9,:) = (/  1.5775e-05,  2.3953e-04, -1.3203e-06/)
Solar_Rtm%Tau_Ray( 9) =  2.5940e-01
Solar_Rtm%Tau_O3( 9) =  0.0000e+00
Solar_Rtm%Tau_CO2( 9) =  0.0000e+00
Solar_Rtm%Tau_CH4( 9) =  0.0000e+00

!SRF = tigr_tpw_trans_ch10_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(10,:) = (/  4.1808e-06,  7.7789e-05, -5.3885e-07/)
Solar_Rtm%Tau_Ray(10) =  1.7429e-01
Solar_Rtm%Tau_O3(10) =  0.0000e+00
Solar_Rtm%Tau_CO2(10) =  0.0000e+00
Solar_Rtm%Tau_CH4(10) =  0.0000e+00

!SRF = tigr_tpw_trans_ch11_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(11,:) = (/  6.0302e-06,  8.1685e-05, -4.6608e-07/)
Solar_Rtm%Tau_Ray(11) =  1.2327e-01
Solar_Rtm%Tau_O3(11) =  2.4974e-05
Solar_Rtm%Tau_CO2(11) =  0.0000e+00
Solar_Rtm%Tau_CH4(11) =  0.0000e+00

!SRF = tigr_tpw_trans_ch12_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(12,:) = (/  4.0052e-05,  1.0060e-03, -8.8589e-06/)
Solar_Rtm%Tau_Ray(12) =  1.0837e-01
Solar_Rtm%Tau_O3(12) =  5.2171e-05
Solar_Rtm%Tau_CO2(12) =  0.0000e+00
Solar_Rtm%Tau_CH4(12) =  0.0000e+00

!SRF = tigr_tpw_trans_ch13_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(13,:) = (/ -1.1911e-05,  6.5363e-04, -6.9043e-07/)
Solar_Rtm%Tau_Ray(13) =  4.8852e-02
Solar_Rtm%Tau_O3(13) =  8.6184e-06
Solar_Rtm%Tau_CO2(13) =  0.0000e+00
Solar_Rtm%Tau_CH4(13) =  0.0000e+00

!SRF = tigr_tpw_trans_ch14_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(14,:) = (/  1.4598e-06,  7.4857e-05, -4.5481e-07/)
Solar_Rtm%Tau_Ray(14) =  4.5046e-02
Solar_Rtm%Tau_O3(14) =  1.7655e-06
Solar_Rtm%Tau_CO2(14) =  0.0000e+00
Solar_Rtm%Tau_CH4(14) =  0.0000e+00

!SRF = tigr_tpw_trans_ch15_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(15,:) = (/ -1.1255e-04,  1.7656e-03, -2.5550e-05/)
Solar_Rtm%Tau_Ray(15) =  3.0544e-02
Solar_Rtm%Tau_O3(15) =  0.0000e+00
Solar_Rtm%Tau_CO2(15) =  0.0000e+00
Solar_Rtm%Tau_CH4(15) =  0.0000e+00

!SRF = tigr_tpw_trans_ch16_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(16,:) = (/ -1.5765e-05,  1.8986e-04, -4.4530e-07/)
Solar_Rtm%Tau_Ray(16) =  1.6757e-02
Solar_Rtm%Tau_O3(16) =  0.0000e+00
Solar_Rtm%Tau_CO2(16) =  0.0000e+00
Solar_Rtm%Tau_CH4(16) =  0.0000e+00

!SRF = tigr_tpw_trans_ch17_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(17,:) = (/  2.9273e-02,  8.2965e-02, -5.5089e-03/)
Solar_Rtm%Tau_Ray(17) =  1.4210e-02
Solar_Rtm%Tau_O3(17) =  0.0000e+00
Solar_Rtm%Tau_CO2(17) =  0.0000e+00
Solar_Rtm%Tau_CH4(17) =  0.0000e+00

!SRF = tigr_tpw_trans_ch18_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(18,:) = (/  2.0286e-01,  3.3230e-01, -2.1097e-02/)
Solar_Rtm%Tau_Ray(18) =  1.2332e-02
Solar_Rtm%Tau_O3(18) =  0.0000e+00
Solar_Rtm%Tau_CO2(18) =  0.0000e+00
Solar_Rtm%Tau_CH4(18) =  0.0000e+00

!SRF = tigr_tpw_trans_ch19_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(19,:) = (/  1.2062e-01,  2.2344e-01, -1.5637e-02/)
Solar_Rtm%Tau_Ray(19) =  1.2332e-02
Solar_Rtm%Tau_O3(19) =  0.0000e+00
Solar_Rtm%Tau_CO2(19) =  0.0000e+00
Solar_Rtm%Tau_CH4(19) =  0.0000e+00

!SRF = tigr_tpw_trans_ch20_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  5.9325e-03,  5.4234e-02, -3.0147e-03/)
Solar_Rtm%Tau_Ray(20) =  3.7429e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.8591e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

!SRF = tigr_tpw_trans_ch26_resp_mod.dat
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2310e+00,  1.6101e+00, -1.4550e-01/)
Solar_Rtm%Tau_Ray(26) =  2.5596e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  2.4893e-04
Solar_Rtm%Tau_CH4(26) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_dnb_srf.txt
Solar_Rtm%Tau_H2O_Coef(44,:) = (/  1.9122e-03,  1.0282e-02, -5.3986e-04/)
Solar_Rtm%Tau_Ray(44) =  5.6484e-02
Solar_Rtm%Tau_O3(44) =  2.4244e-05
Solar_Rtm%Tau_CO2(44) =  0.0000e+00
Solar_Rtm%Tau_CH4(44) =  0.0000e+00
