case(252) 
!SRF = tigr_tpw_trans_ch1_resp_g08.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  8.2380e-04,  6.7217e-03, -3.1961e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.9563e-02
Solar_Rtm%Tau_O3( 1) =  4.4215e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g08.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  1.0190e-03,  2.1607e-02, -1.0798e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.3182e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  3.6962e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(253) 
!SRF = tigr_tpw_trans_ch1_resp_g09.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  8.5965e-04,  6.8685e-03, -3.2377e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.8346e-02
Solar_Rtm%Tau_O3( 1) =  4.3056e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g09.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  5.4444e-04,  1.9333e-02, -8.9357e-04/)
Solar_Rtm%Tau_Ray( 2) =  2.2352e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  3.8803e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(254) 
!SRF = tigr_tpw_trans_ch1_resp_g10.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.0661e-03,  7.6761e-03, -3.5662e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.3895e-02
Solar_Rtm%Tau_O3( 1) =  3.9445e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g10.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  4.6162e-04,  1.9447e-02, -9.4081e-04/)
Solar_Rtm%Tau_Ray( 2) =  2.2829e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  4.0699e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(255) 
!SRF = tigr_tpw_trans_ch1_resp_g11.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.0620e-03,  8.2972e-03, -4.1469e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.1665e-02
Solar_Rtm%Tau_O3( 1) =  3.7031e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g11.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  9.7911e-04,  2.2270e-02, -1.1007e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.4006e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  3.7469e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(256) 
!SRF = tigr_tpw_trans_ch1_resp_g12.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.0331e-03,  7.6943e-03, -3.7572e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.3767e-02
Solar_Rtm%Tau_O3( 1) =  3.9365e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g12.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  1.7562e-03,  2.4023e-02, -1.2267e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.4221e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  3.5827e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(257) 
!SRF = tigr_tpw_trans_ch1_resp_g13.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  2.8386e-04,  4.7715e-03, -1.6917e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.8672e-02
Solar_Rtm%Tau_O3( 1) =  4.5564e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g13.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  2.7935e-03,  2.5992e-02, -1.3777e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.6129e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  8.3670e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(258) 
!SRF = tigr_tpw_trans_ch1_resp_g14.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  3.1050e-04,  4.6602e-03, -1.6077e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.9764e-02
Solar_Rtm%Tau_O3( 1) =  4.8952e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g14.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  2.9646e-03,  2.9737e-02, -1.6860e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.7580e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  7.5234e-03
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

case(259) 
!SRF = tigr_tpw_trans_ch1_resp_g15.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  2.6428e-04,  4.7313e-03, -1.7367e-04/)
Solar_Rtm%Tau_Ray( 1) =  6.9193e-02
Solar_Rtm%Tau_O3( 1) =  4.6483e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_g15.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  2.8286e-03,  2.6194e-02, -1.3701e-03/)
Solar_Rtm%Tau_Ray( 2) =  2.5235e-05
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  1.3535e-02
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00
