image: gitlab.ssec.wisc.edu:5555/cphillips/netcdf_hdf_docker

build:
  stage: build
  script:
    - bash build_ci.sh > build.log
  artifacts:
    paths:
      - build.log
      - clavrx_bin/clavrxorb



# run tests using the binary built before
test:
  stage: test
  script:
    - ./test.sh
