image: gitlab.ssec.wisc.edu:5555/cphillips/netcdf_hdf_docker

build:
  stage: build
  script:
    - bash build/CI/build_ci.sh 2>&1 | tee build.log
  artifacts:
    paths:
      - build.log
      - run/bin/clavrxorb
      - run/bin/comp_asc_des_level2b
      - run/bin/drive_subset_level2b


# run tests using the binary built before
test:
  stage: test
  script:
    - dnf install -y python3 python3-pip
    - pip3 install pyyaml pytest
    - bash test.sh 2>&1 | tee test.log
  artifacts:
    paths:
      - test.log
