case(708) 

!SRF = tigr_tpw_trans_ch1_resp_n05.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  2.9622e-03,  1.3255e-02, -7.9170e-04/)
Solar_Rtm%Tau_Ray(1) =   5.0835e-02
Solar_Rtm%Tau_O3(1) =   2.4109e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n05.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.0892e-02,  4.3456e-02, -3.1441e-03/)
Solar_Rtm%Tau_Ray(2) =   2.2284e-02
Solar_Rtm%Tau_O3(2) =   2.9291e-06
Solar_Rtm%Tau_CO2(2) =   2.3324e-06
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n05.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.4973e-03,  5.2450e-02, -2.8375e-03/)
Solar_Rtm%Tau_Ray(20) =   4.3772e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.4765e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(706) 

!SRF = tigr_tpw_trans_ch1_resp_n06.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  8.4679e-04,  5.1868e-03, -2.0969e-04/)
Solar_Rtm%Tau_Ray(1) =   6.2650e-02
Solar_Rtm%Tau_O3(1) =   5.3333e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n06.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.0063e-02,  4.2681e-02, -3.0403e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1389e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   1.2303e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n06.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.9861e-03,  5.6737e-02, -3.0858e-03/)
Solar_Rtm%Tau_Ray(20) =   4.6129e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.2757e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(707) 

!SRF = tigr_tpw_trans_ch1_resp_n07.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.6763e-04,  4.2391e-03, -1.4129e-04/)
Solar_Rtm%Tau_Ray(1) =   6.2906e-02
Solar_Rtm%Tau_O3(1) =   5.2378e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n07.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.2109e-02,  4.5818e-02, -3.2991e-03/)
Solar_Rtm%Tau_Ray(2) =   2.0918e-02
Solar_Rtm%Tau_O3(2) =   1.2946e-09
Solar_Rtm%Tau_CO2(2) =   1.6935e-06
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n07.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.6003e-03,  6.0205e-02, -3.3547e-03/)
Solar_Rtm%Tau_Ray(20) =   5.2029e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.1402e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(200) 

!SRF = tigr_tpw_trans_ch1_resp_n08.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.3595e-03,  6.0799e-03, -2.8902e-04/)
Solar_Rtm%Tau_Ray(1) =   6.1063e-02
Solar_Rtm%Tau_O3(1) =   5.0561e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n08.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.0130e-02,  4.2949e-02, -3.0902e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1897e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   1.3348e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n08.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  6.5403e-03,  5.1574e-02, -2.9099e-03/)
Solar_Rtm%Tau_Ray(20) =   4.0500e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.5757e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(201) 

!SRF = tigr_tpw_trans_ch1_resp_n09.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  3.1129e-04,  5.2022e-03, -1.9696e-04/)
Solar_Rtm%Tau_Ray(1) =   6.1810e-02
Solar_Rtm%Tau_O3(1) =   4.8304e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n09.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.2501e-02,  4.5262e-02, -3.1829e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1380e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   1.5167e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n09.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.8026e-03,  6.0873e-02, -3.2711e-03/)
Solar_Rtm%Tau_Ray(20) =   5.1878e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.0872e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(202) 

!SRF = tigr_tpw_trans_ch1_resp_n10.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.7154e-04,  4.0978e-03, -1.3142e-04/)
Solar_Rtm%Tau_Ray(1) =   6.3585e-02
Solar_Rtm%Tau_O3(1) =   5.4759e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n10.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.1119e-02,  4.3928e-02, -3.2169e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1156e-02
Solar_Rtm%Tau_O3(2) =   1.3893e-08
Solar_Rtm%Tau_CO2(2) =   2.1888e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n10.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.1089e-03,  5.7738e-02, -3.1820e-03/)
Solar_Rtm%Tau_Ray(20) =   4.7750e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.2622e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(203) 

!SRF = tigr_tpw_trans_ch1_resp_n11.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  3.3394e-04,  5.0860e-03, -1.8345e-04/)
Solar_Rtm%Tau_Ray(1) =   6.1423e-02
Solar_Rtm%Tau_O3(1) =   4.6646e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n11.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.1364e-02,  4.4395e-02, -3.1449e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1597e-02
Solar_Rtm%Tau_O3(2) =   2.1896e-09
Solar_Rtm%Tau_CO2(2) =   3.1995e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n11.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.7493e-03,  5.9600e-02, -3.2033e-03/)
Solar_Rtm%Tau_Ray(20) =   4.9750e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.1463e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(204) 

!SRF = tigr_tpw_trans_ch1_resp_n12.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  5.2672e-04,  5.4110e-03, -2.0067e-04/)
Solar_Rtm%Tau_Ray(1) =   6.0176e-02
Solar_Rtm%Tau_O3(1) =   4.6529e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n12.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.0829e-02,  4.3393e-02, -3.0878e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1482e-02
Solar_Rtm%Tau_O3(2) =   1.5123e-09
Solar_Rtm%Tau_CO2(2) =   1.4345e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n12.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.0864e-03,  5.1323e-02, -2.8780e-03/)
Solar_Rtm%Tau_Ray(20) =   4.3231e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.6220e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(205) 

!SRF = tigr_tpw_trans_ch1_resp_n14.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  4.0156e-04,  5.6986e-03, -2.1450e-04/)
Solar_Rtm%Tau_Ray(1) =   5.9708e-02
Solar_Rtm%Tau_O3(1) =   4.7119e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n14.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.2270e-02,  4.5916e-02, -3.2896e-03/)
Solar_Rtm%Tau_Ray(2) =   2.0770e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   1.2933e-07
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n14.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  6.4129e-03,  5.4838e-02, -3.2564e-03/)
Solar_Rtm%Tau_Ray(20) =   4.4838e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.5294e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(206) 

!SRF = tigr_tpw_trans_ch1_resp_n15.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.5362e-04,  3.8472e-03, -9.9302e-05/)
Solar_Rtm%Tau_Ray(1) =   6.0796e-02
Solar_Rtm%Tau_O3(1) =   5.0768e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n15.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.3315e-02,  4.7734e-02, -3.4759e-03/)
Solar_Rtm%Tau_Ray(2) =   2.0508e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   0.0000e+00
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3a_resp_n15.dat
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -2.6253e-05,  1.0800e-03, -1.0026e-05/)
Solar_Rtm%Tau_Ray(6) =   1.4022e-03
Solar_Rtm%Tau_O3(6) =   0.0000e+00
Solar_Rtm%Tau_CO2(6) =   2.1873e-02
Solar_Rtm%Tau_CH4(6) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n15.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  8.0510e-03,  6.5864e-02, -3.7504e-03/)
Solar_Rtm%Tau_Ray(20) =   5.2809e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.1262e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(207) 

!SRF = tigr_tpw_trans_ch1_resp_n16.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  9.3621e-05,  4.0709e-03, -1.1723e-04/)
Solar_Rtm%Tau_Ray(1) =   6.1114e-02
Solar_Rtm%Tau_O3(1) =   5.1083e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n16.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.4785e-02,  4.9016e-02, -3.5886e-03/)
Solar_Rtm%Tau_Ray(2) =   2.0268e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   0.0000e+00
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3a_resp_n16.dat
Solar_Rtm%Tau_H2O_Coef(6,:) = (/  1.3732e-06,  1.1152e-03, -9.0568e-06/)
Solar_Rtm%Tau_Ray(6) =   1.4177e-03
Solar_Rtm%Tau_O3(6) =   0.0000e+00
Solar_Rtm%Tau_CO2(6) =   2.2059e-02
Solar_Rtm%Tau_CH4(6) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n16.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  8.7787e-03,  6.0215e-02, -3.2763e-03/)
Solar_Rtm%Tau_Ray(20) =   4.8131e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.3300e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(208) 

!SRF = tigr_tpw_trans_ch1_resp_n17.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.0815e-04,  3.7229e-03, -1.0994e-04/)
Solar_Rtm%Tau_Ray(1) =   6.0357e-02
Solar_Rtm%Tau_O3(1) =   5.1410e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n17.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.4834e-02,  4.6764e-02, -3.3763e-03/)
Solar_Rtm%Tau_Ray(2) =   2.0224e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   5.1182e-08
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3a_resp_n17.dat
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -1.8123e-05,  1.0506e-03, -7.6232e-06/)
Solar_Rtm%Tau_Ray(6) =   1.4002e-03
Solar_Rtm%Tau_O3(6) =   0.0000e+00
Solar_Rtm%Tau_CO2(6) =   2.1015e-02
Solar_Rtm%Tau_CH4(6) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n17.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.5547e-03,  5.6550e-02, -3.0821e-03/)
Solar_Rtm%Tau_Ray(20) =   4.7050e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.2760e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(209) 

!SRF = tigr_tpw_trans_ch1_resp_n18.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  4.8872e-05,  3.7923e-03, -1.1940e-04/)
Solar_Rtm%Tau_Ray(1) =   6.0437e-02
Solar_Rtm%Tau_O3(1) =   4.9958e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n18.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.6654e-02,  5.0133e-02, -3.6580e-03/)
Solar_Rtm%Tau_Ray(2) =   1.9821e-02
Solar_Rtm%Tau_O3(2) =   0.0000e+00
Solar_Rtm%Tau_CO2(2) =   0.0000e+00
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3a_resp_n18.dat
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -2.7389e-05,  1.0644e-03, -5.5954e-06/)
Solar_Rtm%Tau_Ray(6) =   1.4084e-03
Solar_Rtm%Tau_O3(6) =   0.0000e+00
Solar_Rtm%Tau_CO2(6) =   2.1507e-02
Solar_Rtm%Tau_CH4(6) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n18.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.3384e-03,  5.4089e-02, -2.9485e-03/)
Solar_Rtm%Tau_Ray(20) =   4.5498e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.3623e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(223) 

!SRF = tigr_tpw_trans_ch1_resp_n19.dat
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  6.7750e-05,  3.8498e-03, -1.2293e-04/)
Solar_Rtm%Tau_Ray(1) =   5.9774e-02
Solar_Rtm%Tau_O3(1) =   4.8241e-05
Solar_Rtm%Tau_CO2(1) =   0.0000e+00
Solar_Rtm%Tau_CH4(1) =   0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_n19.dat
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.1085e-02,  4.1859e-02, -2.9793e-03/)
Solar_Rtm%Tau_Ray(2) =   2.1148e-02
Solar_Rtm%Tau_O3(2) =   6.7735e-09
Solar_Rtm%Tau_CO2(2) =   0.0000e+00
Solar_Rtm%Tau_CH4(2) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3a_resp_n19.dat
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -8.1966e-06,  1.0213e-03, -4.6890e-06/)
Solar_Rtm%Tau_Ray(6) =   1.3898e-03
Solar_Rtm%Tau_O3(6) =   0.0000e+00
Solar_Rtm%Tau_CO2(6) =   2.0799e-02
Solar_Rtm%Tau_CH4(6) =   0.0000e+00

!SRF = tigr_tpw_trans_ch3b_resp_n19.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.5090e-03,  5.7183e-02, -3.1822e-03/)
Solar_Rtm%Tau_Ray(20) =   4.7159e-05
Solar_Rtm%Tau_O3(20) =   0.0000e+00
Solar_Rtm%Tau_CO2(20) =   1.2697e-03
Solar_Rtm%Tau_CH4(20) =   0.0000e+00

case(3) 

!SRF = tigr_tpw_trans_rtcoef_metop_1_avhrr_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.1737e-04,  3.9540e-03, -1.0305e-04/)
Solar_Rtm%Tau_Ray(1) =  6.1163e-02
Solar_Rtm%Tau_O3(1) =  5.1951e-05
Solar_Rtm%Tau_CO2(1) =  0.0000e+00
Solar_Rtm%Tau_CH4(1) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_1_avhrr_srf_ch02.txt
Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.3618e-02,  4.8148e-02, -3.5671e-03/)
Solar_Rtm%Tau_Ray(2) =  2.0358e-02
Solar_Rtm%Tau_O3(2) =  0.0000e+00
Solar_Rtm%Tau_CO2(2) =  0.0000e+00
Solar_Rtm%Tau_CH4(2) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_1_avhrr_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -3.5010e-05,  1.0658e-03, -1.2007e-05/)
Solar_Rtm%Tau_Ray(6) =  1.3939e-03
Solar_Rtm%Tau_O3(6) =  0.0000e+00
Solar_Rtm%Tau_CO2(6) =  2.0432e-02
Solar_Rtm%Tau_CH4(6) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_1_avhrr_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.1410e-03,  5.4959e-02, -3.0015e-03/)
Solar_Rtm%Tau_Ray(20) =  4.7063e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.3137e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(4) 

!SRF = tigr_tpw_trans_rtcoef_metop_2_avhrr_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  1.3007e-04,  3.8614e-03, -1.1091e-04/)
Solar_Rtm%Tau_Ray(1) =  6.1064e-02
Solar_Rtm%Tau_O3(1) =  5.2096e-05
Solar_Rtm%Tau_CO2(1) =  0.0000e+00
Solar_Rtm%Tau_CH4(1) =  0.0000e+00

Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.3199e-02,  4.6504e-02, -3.4555e-03/)
Solar_Rtm%Tau_Ray(2) =  2.0073e-02
Solar_Rtm%Tau_O3(2) =  0.0000e+00
Solar_Rtm%Tau_CO2(2) =  0.0000e+00
Solar_Rtm%Tau_CH4(2) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_2_avhrr_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.8531e-05,  1.0649e-03, -1.1987e-05/)
Solar_Rtm%Tau_Ray(6) =  1.4000e-03
Solar_Rtm%Tau_O3(6) =  0.0000e+00
Solar_Rtm%Tau_CO2(6) =  2.1386e-02
Solar_Rtm%Tau_CH4(6) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_2_avhrr_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  6.7029e-03,  5.9177e-02, -3.1782e-03/)
Solar_Rtm%Tau_Ray(20) =  5.1951e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.1862e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

case(5)

!SRF = tigr_tpw_trans_rtcoef_metop_3_avhrr_srf_ch01.txt
Solar_Rtm%Tau_H2O_Coef(1,:) = (/  9.0751e-05,  3.9376e-03, -1.0720e-04/)
Solar_Rtm%Tau_Ray(1) =  6.1785e-02
Solar_Rtm%Tau_O3(1) =  5.3298e-05
Solar_Rtm%Tau_CO2(1) =  0.0000e+00
Solar_Rtm%Tau_CH4(1) =  0.0000e+00

Solar_Rtm%Tau_H2O_Coef(2,:) = (/  2.2711e-02,  4.3294e-02, -3.0307e-03/)
Solar_Rtm%Tau_Ray(2) =  2.0470e-02
Solar_Rtm%Tau_O3(2) =  0.0000e+00
Solar_Rtm%Tau_CO2(2) =  0.0000e+00
Solar_Rtm%Tau_CH4(2) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_3_avhrr_srf_ch03.txt
Solar_Rtm%Tau_H2O_Coef(6,:) = (/ -2.7990e-05,  1.0701e-03, -1.0282e-05/)
Solar_Rtm%Tau_Ray(6) =  1.3968e-03
Solar_Rtm%Tau_O3(6) =  0.0000e+00
Solar_Rtm%Tau_CO2(6) =  2.0362e-02
Solar_Rtm%Tau_CH4(6) =  0.0000e+00

!SRF = tigr_tpw_trans_rtcoef_metop_3_avhrr_srf_ch04.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  6.7806e-03,  5.8181e-02, -3.2644e-03/)
Solar_Rtm%Tau_Ray(20) =  4.7443e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.2359e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
