case(810) 
!SRF = tigr_tpw_trans_ch1_resp_coms-1.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  1.4714e-03,  9.9685e-03, -4.9934e-04/)
Solar_Rtm%Tau_Ray( 1) =  5.2697e-02
Solar_Rtm%Tau_O3( 1) =  3.3010e-05
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_coms-1.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  7.1117e-03,  5.6163e-02, -3.0117e-03/)
Solar_Rtm%Tau_Ray(20) =  4.8607e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  1.4078e-03
Solar_Rtm%Tau_CH4(20) =  0.0000e+00
