case(224) 

!SRF = tigr_tpw_trans_ch1_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 8,:) = (/  0.0000e+00,  0.0000e+00,  0.0000e+00/)
Solar_Rtm%Tau_Ray( 8) =  3.5038e-01
Solar_Rtm%Tau_O3( 8) =  0.0000e+00
Solar_Rtm%Tau_CO2( 8) =  0.0000e+00
Solar_Rtm%Tau_CH4( 8) =  0.0000e+00

!SRF = tigr_tpw_trans_ch2_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 9,:) = (/  5.9601e-06,  1.7579e-04, -1.6260e-06/)
Solar_Rtm%Tau_Ray( 9) =  2.5728e-01
Solar_Rtm%Tau_O3( 9) =  0.0000e+00
Solar_Rtm%Tau_CO2( 9) =  0.0000e+00
Solar_Rtm%Tau_CH4( 9) =  0.0000e+00

!SRF = tigr_tpw_trans_ch3_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  2.2107e-06,  4.4254e-05, -3.2925e-07/)
Solar_Rtm%Tau_Ray( 3) =  1.7595e-01
Solar_Rtm%Tau_O3( 3) =  5.0749e-09
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_ch4_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  2.9761e-05,  5.6402e-04, -1.4078e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.0535e-01
Solar_Rtm%Tau_O3( 4) =  5.7007e-05
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00

!SRF = tigr_tpw_trans_ch5_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/  5.3694e-06,  5.4977e-04, -1.0484e-05/)
Solar_Rtm%Tau_Ray( 1) =  4.7180e-02
Solar_Rtm%Tau_O3( 1) =  5.1377e-06
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!--- channel 6?

!SRF = tigr_tpw_trans_ch7_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/  5.9361e-05,  2.1869e-03, -6.3343e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.7230e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_ch8_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 5,:) = (/ -9.4945e-05,  6.9109e-03, -2.8043e-04/)
Solar_Rtm%Tau_Ray( 5) =  3.9946e-03
Solar_Rtm%Tau_O3( 5) =  0.0000e+00
Solar_Rtm%Tau_CO2( 5) =  4.9000e-04
Solar_Rtm%Tau_CH4( 5) =  0.0000e+00

!SRF = tigr_tpw_trans_ch9_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.3112e+00,  1.8218e+00, -1.0469e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6079e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.2194e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00

!SRF = tigr_tpw_trans_ch10_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -3.1815e-05,  1.0775e-03, -6.3171e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.4207e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.4843e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00

!SRF = tigr_tpw_trans_ch11_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.1715e-04,  1.2034e-03, -3.5485e-05/)
Solar_Rtm%Tau_Ray( 7) =  3.5168e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  2.7056e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_ch12_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  1.1184e-02,  6.8550e-02, -3.6928e-03/)
Solar_Rtm%Tau_Ray(20) =  5.2127e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  5.8865e-04
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

!SRF = tigr_tpw_trans_ch_dnb_resp_npp.dat
Solar_Rtm%Tau_H2O_Coef(44,:) = (/  1.9072e-03,  1.0856e-02, -5.7611e-04/)
Solar_Rtm%Tau_Ray(44) =  5.4617e-02
Solar_Rtm%Tau_O3(44) =  2.4642e-05
Solar_Rtm%Tau_CO2(44) =  0.0000e+00
Solar_Rtm%Tau_CH4(44) =  0.0000e+00

case(225) 

!SRF = tigr_tpw_trans_noaa20_viirs_m1_srf.txt
Solar_Rtm%Tau_H2O_Coef( 8,:) = (/  0.0000e+00,  0.0000e+00,  0.0000e+00/)
Solar_Rtm%Tau_Ray( 8) =  3.4703e-01
Solar_Rtm%Tau_O3( 8) =  0.0000e+00
Solar_Rtm%Tau_CO2( 8) =  0.0000e+00
Solar_Rtm%Tau_CH4( 8) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m2_srf.txt
Solar_Rtm%Tau_H2O_Coef( 9,:) = (/  9.3674e-06,  1.4208e-04, -6.2620e-07/)
Solar_Rtm%Tau_Ray( 9) =  2.5260e-01
Solar_Rtm%Tau_O3( 9) =  0.0000e+00
Solar_Rtm%Tau_CO2( 9) =  0.0000e+00
Solar_Rtm%Tau_CH4( 9) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m3_srf.txt
Solar_Rtm%Tau_H2O_Coef( 3,:) = (/  3.1455e-06,  5.4775e-05, -2.8300e-07/)
Solar_Rtm%Tau_Ray( 3) =  1.7161e-01
Solar_Rtm%Tau_O3( 3) =  2.2029e-08
Solar_Rtm%Tau_CO2( 3) =  0.0000e+00
Solar_Rtm%Tau_CH4( 3) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m4_srf.txt
Solar_Rtm%Tau_H2O_Coef( 4,:) = (/  4.4679e-06,  2.6894e-04, -2.8111e-06/)
Solar_Rtm%Tau_Ray( 4) =  1.0035e-01
Solar_Rtm%Tau_O3( 4) =  6.7495e-05
Solar_Rtm%Tau_CO2( 4) =  0.0000e+00
Solar_Rtm%Tau_CH4( 4) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m5_srf.txt
Solar_Rtm%Tau_H2O_Coef( 1,:) = (/ -3.6177e-05,  1.2131e-03, -2.8019e-05/)
Solar_Rtm%Tau_Ray( 1) =  4.8140e-02
Solar_Rtm%Tau_O3( 1) =  7.0506e-06
Solar_Rtm%Tau_CO2( 1) =  0.0000e+00
Solar_Rtm%Tau_CH4( 1) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m6_srf.txt
Solar_Rtm%Tau_H2O_Coef(10,:) = (/ -1.2965e-04,  2.7095e-03, -4.6917e-05/)
Solar_Rtm%Tau_Ray(10) =  3.0452e-02
Solar_Rtm%Tau_O3(10) =  0.0000e+00
Solar_Rtm%Tau_CO2(10) =  0.0000e+00
Solar_Rtm%Tau_CH4(10) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m7_srf.txt
Solar_Rtm%Tau_H2O_Coef( 2,:) = (/ -3.2124e-05,  1.0962e-03, -1.5793e-05/)
Solar_Rtm%Tau_Ray( 2) =  1.6749e-02
Solar_Rtm%Tau_O3( 2) =  0.0000e+00
Solar_Rtm%Tau_CO2( 2) =  0.0000e+00
Solar_Rtm%Tau_CH4( 2) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m8_srf.txt
Solar_Rtm%Tau_H2O_Coef( 5,:) = (/ -5.3171e-05,  6.6294e-03, -2.5592e-04/)
Solar_Rtm%Tau_Ray( 5) =  3.9796e-03
Solar_Rtm%Tau_O3( 5) =  0.0000e+00
Solar_Rtm%Tau_CO2( 5) =  4.7997e-04
Solar_Rtm%Tau_CH4( 5) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m9_srf.txt
Solar_Rtm%Tau_H2O_Coef(26,:) = (/  1.2838e+00,  1.8196e+00, -1.0323e-01/)
Solar_Rtm%Tau_Ray(26) =  2.6241e-03
Solar_Rtm%Tau_O3(26) =  0.0000e+00
Solar_Rtm%Tau_CO2(26) =  4.3434e-05
Solar_Rtm%Tau_CH4(26) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m10_srf.txt
Solar_Rtm%Tau_H2O_Coef( 6,:) = (/ -2.9476e-05,  1.0756e-03, -4.7607e-06/)
Solar_Rtm%Tau_Ray( 6) =  1.4057e-03
Solar_Rtm%Tau_O3( 6) =  0.0000e+00
Solar_Rtm%Tau_CO2( 6) =  2.3098e-02
Solar_Rtm%Tau_CH4( 6) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m11_srf.txt
Solar_Rtm%Tau_H2O_Coef( 7,:) = (/ -1.1287e-04,  1.2695e-03, -3.8099e-05/)
Solar_Rtm%Tau_Ray( 7) =  3.5501e-04
Solar_Rtm%Tau_O3( 7) =  0.0000e+00
Solar_Rtm%Tau_CO2( 7) =  2.7284e-06
Solar_Rtm%Tau_CH4( 7) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_m12_srf.txt
Solar_Rtm%Tau_H2O_Coef(20,:) = (/  1.1130e-02,  6.8553e-02, -3.7600e-03/)
Solar_Rtm%Tau_Ray(20) =  5.2425e-05
Solar_Rtm%Tau_O3(20) =  0.0000e+00
Solar_Rtm%Tau_CO2(20) =  6.2672e-04
Solar_Rtm%Tau_CH4(20) =  0.0000e+00

!SRF = tigr_tpw_trans_noaa20_viirs_dnb_srf.txt
Solar_Rtm%Tau_H2O_Coef(44,:) = (/  1.9122e-03,  1.0282e-02, -5.3986e-04/)
Solar_Rtm%Tau_Ray(44) =  5.6484e-02
Solar_Rtm%Tau_O3(44) =  2.4244e-05
Solar_Rtm%Tau_CO2(44) =  0.0000e+00
Solar_Rtm%Tau_CH4(44) =  0.0000e+00
